spring.application.name=expenseTracker
jwt.secret = ${JWT_SECRET}
spring.data.mongodb.uri= ${MONGODB_URI}
spring.data.mongodb.database=expense_tracker
spring.data.mongodb.auto-index-creation=true
gemini.api.key = ${GEMINI_API_KEY}
spring.profiles.active=local