spring.application.name=expenseTracker
jwt.secret = jdcRx6+9oomA6L/8B8ulLUlew26aJD7sMphCzQWZRe4=
spring.data.mongodb.uri=mongodb+srv://moonvp1970_db_user:3P81MYxxYljN32PT@cluster0.qaoxpxc.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=expense_tracker
spring.data.mongodb.auto-index-creation=true
gemini.api.key = AIzaSyByCNDn70pkLKyMotOpu5Wvq0FQjWcA91Y